- name: Ansible(Jenkins) job creation
  hosts: localhost
  vars:
    jenkins_url: http://172.31.95.12:8080
    jenkins_username: admin
    jenkins_password: "{{ lookup('aws_ssm', 'jenkins_password', region='us-east-1' ) }}"
  tasks:
    - name: Create jenkins jobs - Frontend
      community.general.jenkins_job:
        config: "{{ lookup('file','config.xml') }}"
        name: Frontend
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_username}}"

    - name: Create jenkins jobs -Backend
      community.general.jenkins_job:
        config: "{{ lookup('file','config.xml') }}"
        name: Backend
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_username}}"

    - name: Create jenkins jobs - Expense Parameters
      community.general.jenkins_job:
        config: "{{ lookup('file','config.xml') }}"
        name: Expense-Parameters
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_username}}"

    - name: Create jenkins jobs Expense Terraform
      community.general.jenkins_job:
        config: "{{ lookup('file','config.xml') }}"
        name: Expense-Terraform
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_username}}"