- name: Ansible(Jenkins) job creation
  hosts: localhost
  tasks:
    - name: Create jenkins jobs
      community.general.jenkins_job:
        config: "{{ lookup('file','config.xml') }}"
        name: ttest
        password: Canada1991$
        url: http://172.31.95.12:8080
        user: admin