- name: Ansible(Jenkins) job creation
  hosts: localhost
  vars:
    jenkins_url: http://172.31.95.12:8080
    jenkins_username: admin
    jenkins_password: "{{ lookup('aws_ssm', 'jenkins_password', region='us-east-1' ) }}"
  tasks:
    - name: Create jenkinsfile jobs - Frontend
      community.general.jenkins_job:
        config: "{{ lookup('template','config.xml') }}"
        name: Frontend
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_username}}"
      vars:
        repo: frontend

    - name: Create jenkinsfile jobs -Backend
      community.general.jenkins_job:
        config: "{{ lookup('template','config.xml') }}"
        name: Backend
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_username}}"
      vars:
        repo: backend

    - name: Create jenkinsfile jobs - Expense Parameters
      community.general.jenkins_job:
        config: "{{ lookup('template','config.xml') }}"
        name: Expense-Parameters
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_username}}"
      vars:
        repo: parameter-store

    - name: Create jenkinsfile jobs Expense Terraform
      community.general.jenkins_job:
        config: "{{ lookup('template','config.xml') }}"
        name: expense-jenkins-terraform
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_username}}"
      vars:
        repo: expense-jenkins-terraform
