- name: Ansible(Jenkins) job creation
  hosts: localhost
  tasks:
    name: Create jenkins jobs
    community.general.jenkins_job:
      config: "{{ lookup('file', 'templates/config.xml') }}"
      name: test-test
      password: admin123
      url: http://172.31.32.151:8080
      user: admin